Refactored mac file - mainly so I can use it to update and provision

diff --git a/macos/mac b/macos/mac
--- a/macos/mac
+++ b/macos/mac
@@ -49,47 +49,6 @@ create_bash_profile_and_set_it_as_shell_file() {
   shell_file="$HOME/.bash_profile"
 }
 
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-fi
-
-case "$SHELL" in
-  */zsh) :
-    create_zshrc_and_set_it_as_shell_file
-    ;;
-  *)
-    create_bash_profile_and_set_it_as_shell_file
-    if [ -z "$CI" ]; then
-      bold=$(tput bold)
-      normal=$(tput sgr0)
-      echo "Want to switch your shell from the default ${bold}bash${normal} to ${bold}zsh${normal}?"
-      echo "Both work fine for development, and ${bold}zsh${normal} has some extra "
-      echo "features for customization and tab completion."
-      echo "If you aren't sure or don't care, we recommend ${bold}zsh${normal}."
-      echo "Note that you can always switch back to ${bold}bash${normal} if you change your mind."
-      echo "Please see the README for instructions."
-      echo -n "Press ${bold}y${normal} to switch to zsh, ${bold}n${normal} to keep bash: "
-      read -r -n 1 response
-      if [ "$response" = "y" ]; then
-        fancy_echo "=== Getting ready to change your shell to zsh. Please enter your password to continue. ==="
-        echo "=== Note that there won't be visual feedback when you type your password. Type it slowly and press return. ==="
-        echo "=== Press control-c to cancel ==="
-        create_zshrc_and_set_it_as_shell_file
-        chsh -s "$(which zsh)"
-      else
-        fancy_echo "Shell will not be changed."
-      fi
-    else
-      fancy_echo "CI System detected, will not change shells"
-    fi
-    ;;
-esac
-
 brew_is_installed() {
   brew list -1 | grep -Fqx "$1"
 }
@@ -121,275 +80,217 @@ switch_to_latest_ruby() {
   chruby "ruby-$(latest_installed_ruby)"
 }
 
-# shellcheck disable=SC2016
-append_to_file "$shell_file" 'export PATH="$HOME/.bin:$PATH"'
+install_homebrew() {
+  if ! command -v brew >/dev/null; then
+    fancy_echo "Installing Homebrew ..."
+      curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
 
-if ! command -v brew >/dev/null; then
-  fancy_echo "Installing Homebrew ..."
-    curl -fsS \
-      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-
-    # shellcheck disable=SC2016
-    append_to_file "$shell_file" 'export PATH="/usr/local/bin:$PATH"'
-else
-  fancy_echo "Homebrew already installed. Skipping ..."
-fi
-
-# Remove brew-cask since it is now installed as part of brew tap caskroom/cask.
-# See https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.0
-if brew_is_installed 'brew-cask'; then
-  brew uninstall --force 'brew-cask'
-  brew untap caskroom/versions
-fi
-
-fancy_echo "Updating Homebrew formulas ..."
-brew update
-
-fancy_echo "Verifying the Homebrew installation..."
-if brew doctor; then
-  fancy_echo "Your Homebrew installation is good to go."
-else
-  fancy_echo "Your Homebrew installation reported some errors or warnings."
-  echo "If the warnings are related to Python, you can ignore them."
-  echo "Otherwise, review the Homebrew messages to see if any action is needed."
-fi
-
-if brew_is_installed 'cloudfoundry-cli'; then
-  brew uninstall --force cloudfoundry-cli
-fi
-
-fancy_echo "Installing formulas and casks from the Brewfile ..."
-brew bundle
-
-# shellcheck disable=SC2016
-append_to_file "$shell_file" 'eval "$(hub alias -s)"'
-
-fancy_echo 'Checking on Node.js installation...'
-
-if ! brew_is_installed "node"; then
-  if command -v n > /dev/null; then
-    fancy_echo "We recommend using \`nvm\` and not \`n\`."
-    fancy_echo "See https://pages.18f.gov/frontend/#install-npm"
-  elif ! command -v nvm > /dev/null; then
-    fancy_echo 'Installing nvm and lts Node.js and npm...'
-    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
-    export NVM_DIR="$HOME/.nvm"
-    # shellcheck source=/dev/null
-    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-    nvm install node --lts
+      # shellcheck disable=SC2016
+      append_to_file "$shell_file" 'export PATH="/usr/local/bin:$PATH"'
   else
-    fancy_echo 'version manager detected.  Skipping...'
+    fancy_echo "Homebrew already installed. Skipping ..."
   fi
-else
-  brew bundle --file=- <<EOF
+}
+
+update_homebrew_forumlas() {
+  fancy_echo "Updating Homebrew formulas ..."
+  brew update
+}
+
+install_from_brewfile() {
+  fancy_echo "Installing formulas and casks from the Brewfile ..."
+  brew bundle --file=$HOME/macos/Brewfile
+}
+
+install_node_nvm() {
+  fancy_echo 'Checking on Node.js installation...'
+
+  if ! brew_is_installed "node"; then
+    if command -v n > /dev/null; then
+      fancy_echo "We recommend using \`nvm\` and not \`n\`."
+      fancy_echo "See https://pages.18f.gov/frontend/#install-npm"
+    elif ! command -v nvm > /dev/null; then
+      fancy_echo 'Installing nvm and lts Node.js and npm...'
+      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
+      export NVM_DIR="$HOME/.nvm"
+      # shellcheck source=/dev/null
+      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+      nvm install node --lts
+    else
+      fancy_echo 'version manager detected.  Skipping...'
+    fi
+  else
+    brew bundle --file=- <<EOF
   brew 'node'
 EOF
-fi
+  fi
 
-fancy_echo '...Finished Node.js installation checks.'
+  fancy_echo '...Finished Node.js installation checks.'
+}
 
+install_python_pyenv() {
+  fancy_echo 'Checking on Python installation...'
 
-fancy_echo 'Checking on Python installation...'
-
-if ! brew_is_installed "python3"; then
-  brew bundle --file=- <<EOF
+  if ! brew_is_installed "python3"; then
+    brew bundle --file=- <<EOF
   brew 'pyenv'
   brew 'pyenv-virtualenv'
   brew 'pyenv-virtualenvwrapper'
 EOF
-  # shellcheck disable=SC2016
-  append_to_file "$shell_file" 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi'
-  # shellcheck disable=SC2016
-  append_to_file "$shell_file" 'if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi'
+    # shellcheck disable=SC2016
+    append_to_file "$shell_file" 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi'
+    # shellcheck disable=SC2016
+    append_to_file "$shell_file" 'if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi'
 
-  # pyenv currently doesn't have a convenience version to use, e.g., "latest",
-  # so we check for the latest version against Homebrew instead.
-  latest_python_3="$(brew info python3 | egrep -o "3\.\d+\.\d+" | head -1)"
+    # pyenv currently doesn't have a convenience version to use, e.g., "latest",
+    # so we check for the latest version against Homebrew instead.
+    latest_python_3="$(brew info python3 | egrep -o "3\.\d+\.\d+" | head -1)"
 
-  if ! pyenv versions | ag "$latest_python_3" > /dev/null; then
-    pyenv install "$latest_python_3"
-    pyenv global "$latest_python_3"
-    pyenv rehash
-  fi
-else
-  brew bundle --file=- <<EOF
-  brew 'python3'
-EOF
-fi
-
-if ! brew_is_installed "pyenv-virtualenvwrapper"; then
-  if ! pip3 list | ag "virtualenvwrapper" > /dev/null; then
-    fancy_echo 'Installing virtualenvwrapper...'
-    pip3 install virtualenvwrapper
-    append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3'
-    append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv'
-    append_to_file "$shell_file" 'source /usr/local/bin/virtualenvwrapper.sh'
-  fi
-fi
-
-fancy_echo '...Finished Python installation checks.'
-
-
-fancy_echo 'Checking on Ruby installation...'
-
-append_to_file "$HOME/.gemrc" 'gem: --no-document'
-
-if command -v rbenv >/dev/null || command -v rvm >/dev/null; then
-  fancy_echo 'We recommend chruby and ruby-install over RVM or rbenv'
-else
-  if ! brew_is_installed "chruby"; then
-    fancy_echo 'Installing chruby, ruby-install, and the latest Ruby...'
-
-    brew bundle --file=- <<EOF
-    brew 'chruby'
-    brew 'ruby-install'
-EOF
-
-    append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
-    append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
-
-    ruby-install ruby
-
-    append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
-
-    switch_to_latest_ruby
+    if ! pyenv versions | ag "$latest_python_3" > /dev/null; then
+      pyenv install "$latest_python_3"
+      pyenv global "$latest_python_3"
+      pyenv rehash
+    fi
   else
     brew bundle --file=- <<EOF
+  brew 'python3'
+EOF
+  fi
+
+  if ! brew_is_installed "pyenv-virtualenvwrapper"; then
+    if ! pip3 list | ag "virtualenvwrapper" > /dev/null; then
+      fancy_echo 'Installing virtualenvwrapper...'
+      pip3 install virtualenvwrapper
+      append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3'
+      append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv'
+      append_to_file "$shell_file" 'source /usr/local/bin/virtualenvwrapper.sh'
+    fi
+  fi
+
+  fancy_echo '...Finished Python installation checks.'
+}
+
+install_ruby_chruby() {
+  fancy_echo 'Checking on Ruby installation...'
+
+  append_to_file "$HOME/.gemrc" 'gem: --no-document'
+
+  if command -v rbenv >/dev/null || command -v rvm >/dev/null; then
+    fancy_echo 'We recommend chruby and ruby-install over RVM or rbenv'
+  else
+    if ! brew_is_installed "chruby"; then
+      fancy_echo 'Installing chruby, ruby-install, and the latest Ruby...'
+
+      brew bundle --file=- <<EOF
     brew 'chruby'
     brew 'ruby-install'
 EOF
-    fancy_echo 'Checking if a newer version of Ruby is available...'
-    switch_to_latest_ruby
 
-    ruby-install --latest > /dev/null
-    latest_stable_ruby="$(cat < "$HOME/.cache/ruby-install/ruby/stable.txt" | tail -n1)"
+      append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
+      append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
 
-    if ! [ "$latest_stable_ruby" = "$(latest_installed_ruby)" ]; then
-      fancy_echo "Installing latest stable Ruby version: $latest_stable_ruby"
       ruby-install ruby
+
+      append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
+
+      switch_to_latest_ruby
     else
-      fancy_echo 'You have the latest version of Ruby'
+      brew bundle --file=- <<EOF
+    brew 'chruby'
+    brew 'ruby-install'
+EOF
+      fancy_echo 'Checking if a newer version of Ruby is available...'
+      switch_to_latest_ruby
+
+      ruby-install --latest > /dev/null
+      latest_stable_ruby="$(cat < "$HOME/.cache/ruby-install/ruby/stable.txt" | tail -n1)"
+
+      if ! [ "$latest_stable_ruby" = "$(latest_installed_ruby)" ]; then
+        fancy_echo "Installing latest stable Ruby version: $latest_stable_ruby"
+        ruby-install ruby
+      else
+        fancy_echo 'You have the latest version of Ruby'
+      fi
     fi
   fi
-fi
 
-fancy_echo 'Updating Rubygems...'
-gem update --system
+  fancy_echo 'Updating Rubygems...'
+  gem update --system
 
-gem_install_or_update 'bundler'
+  gem_install_or_update 'bundler'
 
-fancy_echo "Configuring Bundler ..."
-number_of_cores=$(sysctl -n hw.ncpu)
-bundle config --global jobs $((number_of_cores - 1))
+  fancy_echo "Configuring Bundler ..."
+  number_of_cores=$(sysctl -n hw.ncpu)
+  bundle config --global jobs $((number_of_cores - 1))
 
-fancy_echo '...Finished Ruby installation checks.'
+  fancy_echo '...Finished Ruby installation checks.'
+}
 
-if [ -f "$HOME/.laptop.local" ]; then
-  # shellcheck source=/dev/null
-  . "$HOME/.laptop.local"
-fi
+set_macos_defaults() {
+  source $HOME/macos/defaults.sh
+}
 
-curl -s https://raw.githubusercontent.com/18F/laptop/master/seekrets-install | sh -
+provision() {
+  # shellcheck disable=SC2154
+  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
 
-fancy_echo 'Configuring OS X'
+  set -e
 
-append_to_file "$HOME/.zshrc" 'export PATH="$PATH:/usr/local/opt/go/libexec/bin"'
+  if [ ! -d "$HOME/.bin/" ]; then
+    mkdir "$HOME/.bin"
+  fi
 
-# Show battery life percentage.
-defaults write com.apple.menuextra.battery ShowPercent -string "YES"
+  fancy_echo "=== Getting ready to change your shell to zsh. Please enter your password to continue. ==="
+  echo "=== Note that there won't be visual feedback when you type your password. Type it slowly and press return. ==="
+  echo "=== Press control-c to cancel ==="
+  create_zshrc_and_set_it_as_shell_file
+  chsh -s "$(which zsh)"
 
-# Reveal IP address, hostname, OS version, etc. when clicking the clock
-# in the login window
-sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
+  # shellcheck disable=SC2016
+  append_to_file "$shell_file" 'export PATH="$HOME/.bin:$PATH"'
 
-# Check for software updates daily, not just once per week
-defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
+  install_homebrew
+  update_homebrew_forumlas
 
-# Download newly available updates in background
-defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1
+  # shellcheck disable=SC2016
+  append_to_file "$shell_file" 'eval "$(hub alias -s)"'
 
-# Install System data files & security updates
-defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1
+  install_node_nvm
+  install_python_pyenv
+  install_ruby_chruby
 
-# Automatically download apps purchased on other Macs
-defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1
+  if [ -f "$HOME/.laptop.local" ]; then
+    # shellcheck source=/dev/null
+    . "$HOME/.laptop.local"
+  fi
 
-# Turn on app auto-update
-defaults write com.apple.commerce AutoUpdate -bool true
+  if [ -f "/usr/local/bin/git-seekret" ]; then
+    curl -s https://raw.githubusercontent.com/18F/laptop/master/seekrets-install | sh -
+  fi
 
-# Allow the App Store to reboot machine on macOS updates
-defaults write com.apple.commerce AutoUpdateRestartRequired -bool true
+  append_to_file "$HOME/.zshrc.local" 'export PATH="$PATH:/usr/local/opt/go/libexec/bin"'
 
-# Require password immediately after sleep or screen saver begins
-defaults write com.apple.screensaver askForPassword -int 1
-defaults write com.apple.screensaver askForPasswordDelay -int 0
+  fancy_echo 'Configuring OS X'
 
-# Save screenshots to the downlaods.
-defaults write com.apple.screencapture location "$HOME/Downloads/"
+  set_macos_defaults
 
-# Trackpad: enable tap to click for this user and for the login screen
-defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
-defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
-defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
-sudo defaults write com.apple.AppleMultitouchTrackpad Clicking 1
+  fancy_echo 'All done! Some of these changes require a restart to take effect.'
+}
 
-# Finder: show all filename extensions
-defaults write NSGlobalDomain AppleShowAllExtensions -bool true
+update() {
+  fancy_echo 'Updating machine'
 
-# Disable the warning when changing a file extension
-defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
+  install_from_brewfile
+  set_macos_defaults
 
-# Enable the Develop menu and the Web Inspector in Safari
-defaults write com.apple.Safari IncludeDevelopMenu -bool true
-defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
-defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
+  fancy_echo 'All done!'
+}
 
-# Minimize windows into their application’s icon
-defaults write com.apple.dock minimize-to-application -bool true
-
-# Disable Dashboard
-defaults write com.apple.dashboard mcx-disabled -bool true
-
-# Don’t show Dashboard as a Space
-defaults write com.apple.dock dashboard-in-overlay -bool true
-
-# Don’t automatically rearrange Spaces based on most recent use
-defaults write com.apple.dock mru-spaces -bool false
-
-# Automatically hide and show the Dock
-defaults write com.apple.dock autohide -bool true
-
-# Only use UTF-8 in Terminal.app
-defaults write com.apple.terminal StringEncodings -array 4
-
-# Don’t display the annoying prompt when quitting iTerm
-defaults write com.googlecode.iterm2 PromptOnQuit -bool false
-
-# Show the main window when launching Activity Monitor
-defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
-
-# Visualize CPU usage in the Activity Monitor Dock icon
-defaults write com.apple.ActivityMonitor IconType -int 5
-
-# Show all processes in Activity Monitor
-defaults write com.apple.ActivityMonitor ShowCategory -int 0
-
-# Sort Activity Monitor results by CPU usage
-defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
-defaults write com.apple.ActivityMonitor SortDirection -int 0
-
-# Prevent Photos from opening automatically when devices are plugged in
-defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
-
-# Disable the all too sensitive backswipe on trackpads
-defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
-defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false
-
-# Disable the all too sensitive backswipe on Magic Mouse
-defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
-defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false
-
-# Disable spotlight - I prefer alfred
-sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
-
-fancy_echo 'All done! Some of these changes require a restart to take effect.'
+case "$1" in
+  */install) :
+    provision
+    ;;
+  *)
+    update
+    ;;
+esac
