Undo some previous changes

diff --git a/macos/mac b/macos/mac
--- a/macos/mac
+++ b/macos/mac
@@ -103,12 +103,6 @@ install_from_brewfile() {
 }
 
 install_node_nvm() {
-  # shellcheck disable=SC2154
-  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-  set -e
-
-
   fancy_echo 'Checking on Node.js installation...'
 
   if ! brew_is_installed "node"; then
@@ -237,6 +231,11 @@ set_macos_defaults() {
 }
 
 provision() {
+  # shellcheck disable=SC2154
+  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+  set -e
+
   if [ ! -d "$HOME/.bin/" ]; then
     mkdir "$HOME/.bin"
   fi
@@ -296,11 +295,6 @@ update() {
 
   fancy_echo 'All done!'
 }
-
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
 
 case "$1" in
   install) :
