Moved the trap

diff --git a/macos/mac b/macos/mac
--- a/macos/mac
+++ b/macos/mac
@@ -231,11 +231,6 @@ set_macos_defaults() {
 }
 
 provision() {
-  # shellcheck disable=SC2154
-  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-  set -e
-
   if [ ! -d "$HOME/.bin/" ]; then
     mkdir "$HOME/.bin"
   fi
@@ -295,6 +290,11 @@ update() {
 
   fancy_echo 'All done!'
 }
+
+# shellcheck disable=SC2154
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
 
 case "$1" in
   install) :
