Some amount of refactoring to see if I can fix nvm

diff --git a/macos/mac b/macos/mac
--- a/macos/mac
+++ b/macos/mac
@@ -102,179 +102,8 @@ install_from_brewfile() {
   brew bundle --file=$HOME/macos/Brewfile
 }
 
-install_node_nvm() {
-  fancy_echo 'Checking on Node.js installation...'
-
-  if ! brew_is_installed "node"; then
-    if command -v n > /dev/null; then
-      fancy_echo "We recommend using \`nvm\` and not \`n\`."
-      fancy_echo "See https://pages.18f.gov/frontend/#install-npm"
-    elif ! command -v nvm > /dev/null; then
-      fancy_echo 'Installing nvm and lts Node.js and npm...'
-      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
-      export NVM_DIR="$HOME/.nvm"
-      # shellcheck source=/dev/null
-      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-      nvm install node --lts
-    else
-      fancy_echo 'version manager detected.  Skipping...'
-    fi
-  else
-    brew bundle --file=- <<EOF
-  brew 'node'
-EOF
-  fi
-
-  fancy_echo '...Finished Node.js installation checks.'
-}
-
-install_python_pyenv() {
-  fancy_echo 'Checking on Python installation...'
-
-  if ! brew_is_installed "python3"; then
-    brew bundle --file=- <<EOF
-  brew 'pyenv'
-  brew 'pyenv-virtualenv'
-  brew 'pyenv-virtualenvwrapper'
-EOF
-    # shellcheck disable=SC2016
-    append_to_file "$shell_file" 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi'
-    # shellcheck disable=SC2016
-    append_to_file "$shell_file" 'if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi'
-
-    # pyenv currently doesn't have a convenience version to use, e.g., "latest",
-    # so we check for the latest version against Homebrew instead.
-    latest_python_3="$(brew info python3 | egrep -o "3\.\d+\.\d+" | head -1)"
-
-    if ! pyenv versions | ag "$latest_python_3" > /dev/null; then
-      pyenv install "$latest_python_3"
-      pyenv global "$latest_python_3"
-      pyenv rehash
-    fi
-  else
-    brew bundle --file=- <<EOF
-  brew 'python3'
-EOF
-  fi
-
-  if ! brew_is_installed "pyenv-virtualenvwrapper"; then
-    if ! pip3 list | ag "virtualenvwrapper" > /dev/null; then
-      fancy_echo 'Installing virtualenvwrapper...'
-      pip3 install virtualenvwrapper
-      append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3'
-      append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv'
-      append_to_file "$shell_file" 'source /usr/local/bin/virtualenvwrapper.sh'
-    fi
-  fi
-
-  fancy_echo '...Finished Python installation checks.'
-}
-
-install_ruby_chruby() {
-  fancy_echo 'Checking on Ruby installation...'
-
-  append_to_file "$HOME/.gemrc" 'gem: --no-document'
-
-  if command -v rbenv >/dev/null || command -v rvm >/dev/null; then
-    fancy_echo 'We recommend chruby and ruby-install over RVM or rbenv'
-  else
-    if ! brew_is_installed "chruby"; then
-      fancy_echo 'Installing chruby, ruby-install, and the latest Ruby...'
-
-      brew bundle --file=- <<EOF
-    brew 'chruby'
-    brew 'ruby-install'
-EOF
-
-      append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
-      append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
-
-      ruby-install ruby
-
-      append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
-
-      switch_to_latest_ruby
-    else
-      brew bundle --file=- <<EOF
-    brew 'chruby'
-    brew 'ruby-install'
-EOF
-      fancy_echo 'Checking if a newer version of Ruby is available...'
-      switch_to_latest_ruby
-
-      ruby-install --latest > /dev/null
-      latest_stable_ruby="$(cat < "$HOME/.cache/ruby-install/ruby/stable.txt" | tail -n1)"
-
-      if ! [ "$latest_stable_ruby" = "$(latest_installed_ruby)" ]; then
-        fancy_echo "Installing latest stable Ruby version: $latest_stable_ruby"
-        ruby-install ruby
-      else
-        fancy_echo 'You have the latest version of Ruby'
-      fi
-    fi
-  fi
-
-  fancy_echo 'Updating Rubygems...'
-  gem update --system
-
-  gem_install_or_update 'bundler'
-
-  fancy_echo "Configuring Bundler ..."
-  number_of_cores=$(sysctl -n hw.ncpu)
-  bundle config --global jobs $((number_of_cores - 1))
-
-  fancy_echo '...Finished Ruby installation checks.'
-}
-
 set_macos_defaults() {
   source $HOME/macos/defaults.sh
-}
-
-provision() {
-  # shellcheck disable=SC2154
-  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-  set -e
-
-  if [ ! -d "$HOME/.bin/" ]; then
-    mkdir "$HOME/.bin"
-  fi
-
-  fancy_echo "=== Getting ready to change your shell to zsh. Please enter your password to continue. ==="
-  echo "=== Note that there won't be visual feedback when you type your password. Type it slowly and press return. ==="
-  echo "=== Press control-c to cancel ==="
-  create_zshrc_and_set_it_as_shell_file
-  chsh -s "$(which zsh)"
-
-  # shellcheck disable=SC2016
-  append_to_file "$shell_file" 'export PATH="$HOME/.bin:$PATH"'
-
-  install_homebrew
-  update_homebrew_forumlas
-
-  # shellcheck disable=SC2016
-  append_to_file "$shell_file" 'eval "$(hub alias -s)"'
-
-  install_node_nvm
-  install_python_pyenv
-  install_ruby_chruby
-
-  if [ -f "$HOME/.laptop.local" ]; then
-    # shellcheck source=/dev/null
-    . "$HOME/.laptop.local"
-  fi
-
-  if [ -f "/usr/local/bin/git-seekret" ]; then
-    curl -s https://raw.githubusercontent.com/18F/laptop/master/seekrets-install | sh -
-  fi
-
-  append_to_file "$HOME/.zshrc.local" 'export PATH="$PATH:/usr/local/opt/go/libexec/bin"'
-
-  fancy_echo 'Configuring OS X'
-
-  set_macos_defaults
-
-  fancy_echo 'All done! Some of these changes require a restart to take effect.'
 }
 
 update() {
@@ -298,7 +127,172 @@ update() {
 
 case "$1" in
   install) :
-    provision
+    # shellcheck disable=SC2154
+    trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+    set -e
+
+    if [ ! -d "$HOME/.bin/" ]; then
+      mkdir "$HOME/.bin"
+    fi
+
+    fancy_echo "=== Getting ready to change your shell to zsh. Please enter your password to continue. ==="
+    echo "=== Note that there won't be visual feedback when you type your password. Type it slowly and press return. ==="
+    echo "=== Press control-c to cancel ==="
+    create_zshrc_and_set_it_as_shell_file
+    chsh -s "$(which zsh)"
+
+    # shellcheck disable=SC2016
+    append_to_file "$shell_file" 'export PATH="$HOME/.bin:$PATH"'
+
+    install_homebrew
+    update_homebrew_forumlas
+
+    # shellcheck disable=SC2016
+    append_to_file "$shell_file" 'eval "$(hub alias -s)"'
+
+    # --- Node
+
+    fancy_echo 'Checking on Node.js installation...'
+
+    if ! brew_is_installed "node"; then
+      if command -v n > /dev/null; then
+        fancy_echo "We recommend using \`nvm\` and not \`n\`."
+        fancy_echo "See https://pages.18f.gov/frontend/#install-npm"
+      elif ! command -v nvm > /dev/null; then
+        fancy_echo 'Installing nvm and lts Node.js and npm...'
+        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
+        export NVM_DIR="$HOME/.nvm"
+        # shellcheck source=/dev/null
+        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+        nvm install node --lts -v
+      else
+        fancy_echo 'version manager detected.  Skipping...'
+      fi
+    else
+      brew bundle --file=- <<EOF
+    brew 'node'
+EOF
+    fi
+
+    fancy_echo '...Finished Node.js installation checks.'
+
+    # --- Python
+
+    fancy_echo 'Checking on Python installation...'
+
+    if ! brew_is_installed "python3"; then
+      brew bundle --file=- <<EOF
+    brew 'pyenv'
+    brew 'pyenv-virtualenv'
+    brew 'pyenv-virtualenvwrapper'
+EOF
+      # shellcheck disable=SC2016
+      append_to_file "$shell_file" 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi'
+      # shellcheck disable=SC2016
+      append_to_file "$shell_file" 'if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi'
+
+      # pyenv currently doesn't have a convenience version to use, e.g., "latest",
+      # so we check for the latest version against Homebrew instead.
+      latest_python_3="$(brew info python3 | egrep -o "3\.\d+\.\d+" | head -1)"
+
+      if ! pyenv versions | ag "$latest_python_3" > /dev/null; then
+        pyenv install "$latest_python_3"
+        pyenv global "$latest_python_3"
+        pyenv rehash
+      fi
+    else
+      brew bundle --file=- <<EOF
+    brew 'python3'
+EOF
+    fi
+
+    if ! brew_is_installed "pyenv-virtualenvwrapper"; then
+      if ! pip3 list | ag "virtualenvwrapper" > /dev/null; then
+        fancy_echo 'Installing virtualenvwrapper...'
+        pip3 install virtualenvwrapper
+        append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3'
+        append_to_file "$shell_file" 'export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv'
+        append_to_file "$shell_file" 'source /usr/local/bin/virtualenvwrapper.sh'
+      fi
+    fi
+
+    fancy_echo '...Finished Python installation checks.'
+
+    # --- Ruby
+
+    fancy_echo 'Checking on Ruby installation...'
+
+    append_to_file "$HOME/.gemrc" 'gem: --no-document'
+
+    if command -v rbenv >/dev/null || command -v rvm >/dev/null; then
+      fancy_echo 'We recommend chruby and ruby-install over RVM or rbenv'
+    else
+      if ! brew_is_installed "chruby"; then
+        fancy_echo 'Installing chruby, ruby-install, and the latest Ruby...'
+
+        brew bundle --file=- <<EOF
+      brew 'chruby'
+      brew 'ruby-install'
+EOF
+
+        append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
+        append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
+
+        ruby-install ruby
+
+        append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
+
+        switch_to_latest_ruby
+      else
+        brew bundle --file=- <<EOF
+      brew 'chruby'
+      brew 'ruby-install'
+EOF
+        fancy_echo 'Checking if a newer version of Ruby is available...'
+        switch_to_latest_ruby
+
+        ruby-install --latest > /dev/null
+        latest_stable_ruby="$(cat < "$HOME/.cache/ruby-install/ruby/stable.txt" | tail -n1)"
+
+        if ! [ "$latest_stable_ruby" = "$(latest_installed_ruby)" ]; then
+          fancy_echo "Installing latest stable Ruby version: $latest_stable_ruby"
+          ruby-install ruby
+        else
+          fancy_echo 'You have the latest version of Ruby'
+        fi
+      fi
+    fi
+
+    fancy_echo 'Updating Rubygems...'
+    gem update --system
+
+    gem_install_or_update 'bundler'
+
+    fancy_echo "Configuring Bundler ..."
+    number_of_cores=$(sysctl -n hw.ncpu)
+    bundle config --global jobs $((number_of_cores - 1))
+
+    fancy_echo '...Finished Ruby installation checks.'
+
+    install_ruby_chruby
+
+    if [ -f "$HOME/.laptop.local" ]; then
+      # shellcheck source=/dev/null
+      . "$HOME/.laptop.local"
+    fi
+
+    if [ -f "/usr/local/bin/git-seekret" ]; then
+      curl -s https://raw.githubusercontent.com/18F/laptop/master/seekrets-install | sh -
+    fi
+
+    append_to_file "$HOME/.zshrc.local" 'export PATH="$PATH:/usr/local/opt/go/libexec/bin"'
+
+    fancy_echo 'Configuring OS X'
+
+    set_macos_defaults
+
+    fancy_echo 'All done! Some of these changes require a restart to take effect.'
     ;;
   *)
     update $2
